### PR TITLE
#44 Parsing - Loaded Data - Based on Master

### PR DESCRIPTION
**Pull request by bae-junghwan**
This PR aims to fix parsing issues and create misc. changes as described in issue #44 
Fixed the parsing errors on the Loaded Data page.
Also made a small fix to grammar in one of the sentences on the page.
Adjusted width of table.
Reformatted code

---

### Changes made:
- LoadedData.html
  - Formatted code so that each opening tag matches the same tab spacing as its closing tag
  - Fixed parsing errors
    - Omitted obsolete or duplicate attributes
    - Removed duplicate / unnecessary closing divs
    - Moved some divs around
 
- styles.css
  - Added left and right borders to table

---
**Current Page**
image
image
---
**Previous Page**
image
image
---

### CODE REVIEW

**Review by michellemcgowan — COMMENTED** [review]
Very nice @bae-junghwan! No more parsing errors <];) I like the shortened table too! 

Just one thing b/c if I get called out for it YOU are getting called out for it. NOT THAT IT IS OUR FAULT OR ANYTHING. Just that there aren't any `<tbody>` or `<thead>` tags for the table which would make it more accessible to peeps using screen readers. But, good job!!

**Review by Kelvyn-Meyers — CHANGES_REQUESTED** [review]
Hi @bae-junghwan,

Very nice work fixing all the parsing errors on this page and reformatting the code to be more readable! The "Plan Revision Statuses for NFS" link needs to be re-applied. I believe you accidentally deleted the anchor-tag when pasting the new sentence. After that, and Michelle's request, we should be good to go!

**Comment by bae-junghwan** [comment]
Hi @Kelvyn-Meyers and @michellemcgowan - I've added the `<thead>` and `<tbody>` tags. I've also fixed the accidentally deleted anchor tags for "Plan Revision Statuses for NFS"

**Review by Kelvyn-Meyers — APPROVED** [review]
Everything looks good, thanks @bae-junghwan! Ready to merge.

**Pull request merged**
