### PR TITLE
#2 Info and Relationships - Loaded Data - Based on master

### PR DESCRIPTION
**Pull request by michellemcgowan**
Addresses issue #2. Table cells were not associated with the state names 

<h2>Code Changes</h2>

- made state names into table headers
- scope for horizontal headers is row and for vertical headers is col 
- cells associated w/ both horizontal headers and vertical headers
image

### CODE REVIEW

**Review by bae-junghwan — APPROVED** [review]
Hi Michelle. Took a look at everything. The table for States and Territories are looking good. Great job!

**Review by Kelvyn-Meyers — CHANGES_REQUESTED** [review]
Hi @michellemcgowan,

Nice work with all of those changes! One small thing: the tables themselves could make use of programmatic labels just so that screen readers can better announce what table has the current attention of the user.

You can probably make use of `aria-labelledby` to point to the headers above each table for this:

image

**Comment by michellemcgowan** [comment]
image
image

Now how programmatic labels

**Review by Kelvyn-Meyers — APPROVED** [review]
Perfect, thanks @michellemcgowan! Ready to merge.

**Pull request merged**
